In [27]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd

In [37]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa']) #small dataset

In [28]:
model = Sequential()
model.add(Dense(2, activation='linear',input_dim=2)) #using linear activation for regression problem
model.add(Dense(1, activation='linear'))

In [29]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [30]:
model.get_weights() # keras is assigning random weights

[array([[-0.18855095, -0.23956424],
        [ 0.29217303, -1.1945776 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.06106138],
        [ 0.41357887]], dtype=float32),
 array([0.], dtype=float32)]

In [31]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [32]:
model.set_weights(new_weights) #but we will overwrite them with simple w with 1 and b with 0

In [33]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [43]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)  #using Adam optimizer
model.compile(loss='mean_squared_error',optimizer=optimizer) #calculating mean squared error

In [46]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1) # after every time we rerun it got better

Epoch 1/75
4/4 [==============================] - 0s 4ms/step - loss: 0.0419
Epoch 2/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0415
Epoch 3/75
4/4 [==============================] - 0s 6ms/step - loss: 0.0413
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0410
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 0.0415
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 0.0410
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0413
Epoch 8/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0404
Epoch 9/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0400
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0398
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 0.0399
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 0.0398
Epoch 13/75
4/4 [==============================] - 0s 4ms/step - loss: 0.

In [48]:
model.get_weights() #after every iteration weights changes

[array([[-0.13814676, -0.13814676],
        [ 0.6203912 ,  0.6203912 ]], dtype=float32),
 array([0.17570153, 0.17570153], dtype=float32),
 array([[0.4987826],
        [0.4987826]], dtype=float32),
 array([0.18597715], dtype=float32)]